### PR TITLE
Reentrant version of the runtime

### PR DESCRIPTION
**Pull request by madmann91**
This branch makes the runtime reentrant. It seems that the CUDA platform works (stincilla and the traversal code pass). I have tested stincilla with the OpenCL platform, and the following tests fail:

- aobench
- multi_gpu
- alloc_gpu_unified
- median

And vcycle takes forever to compile (I suspect an infinite loop, but I was only compiling for around 10mins with Impala in debug mode).

@richardmembarth Are these results correct? Shall we merge the branch?

### CODE REVIEW

**Comment by richardmembarth** [comment]
All tests should pass apart from median.

* multi_gpu passes on my system (you need multiple OpenCL devices)
* alloc_gpu_unified requires an OpenCL 2.0 platform
* aobench and vcycle fail - those pass structs as argument, I guess something is broken there. vcycle takes ~10mins in release build, ~30mins in debug build.

**Comment by madmann91** [comment]
The structure passing issue should now be fixed. I think the branch is ready for merging.

**Comment by madmann91** [comment]
The only tests that now fail are multi_gpu, alloc_gpu_unified, and median. All other tests pass on my system (I only have one GPU and no OpenCL 2.0 platform).

**Comment by richardmembarth** [comment]
Then we can merge now.

**Pull request closed without merging**
