### PR TITLE
Add kernel name prefix

### PR DESCRIPTION
**Pull request by PearCoding**
Add optional kernel prefix for IR debugging and diagnosis.
Changes internal intrinsics, but the Accelerator interface is only extended and is backwards compatible.

### CODE REVIEW

**Comment by PearCoding** [comment]
Tested it with Rodent on Impala and Artic

**Comment by PearCoding** [comment]
Another way of handling this is to only change the accelerator interface:

```
struct Accelerator {
    work          : WorkItem,
    exec          : fn(fn() -> ()) -> fn((i32, i32, i32), (i32, i32, i32)) -> (), // fn(grid, block)->()
    sync          : fn() -> (),
    alloc         : fn(i64) -> Buffer,
    alloc_unified : fn(i64) -> Buffer,
    barrier       : fn() -> ()
}
```

This will allow the name of a closure to be properly passed down to the intrinsic and no Thorin change would be necessary. Here an example for nvvm:

```
fn @nvvm_accelerator(dev: i32) = Accelerator {
    work = WorkItem {
        tidx  = nvvm_read_ptx_sreg_tid_x,
        tidy  = nvvm_read_ptx_sreg_tid_y,
        tidz  = nvvm_read_ptx_sreg_tid_z,
        bidx  = nvvm_read_ptx_sreg_ctaid_x,
        bidy  = nvvm_read_ptx_sreg_ctaid_y,
        bidz  = nvvm_read_ptx_sreg_ctaid_z,
        gidx  = @|| nvvm_read_ptx_sreg_tid_x() + nvvm_read_ptx_sreg_ntid_x() * nvvm_read_ptx_sreg_ctaid_x(),
        gidy  = @|| nvvm_read_ptx_sreg_tid_y() + nvvm_read_ptx_sreg_ntid_y() * nvvm_read_ptx_sreg_ctaid_y(),
        gidz  = @|| nvvm_read_ptx_sreg_tid_z() + nvvm_read_ptx_sreg_ntid_z() * nvvm_read_ptx_sreg_ctaid_z(),
        bdimx = nvvm_read_ptx_sreg_ntid_x,
        bdimy = nvvm_read_ptx_sreg_ntid_y,
        bdimz = nvvm_read_ptx_sreg_ntid_z,
        gdimx = @|| nvvm_read_ptx_sreg_nctaid_x() * nvvm_read_ptx_sreg_ntid_x(),
        gdimy = @|| nvvm_read_ptx_sreg_nctaid_y() * nvvm_read_ptx_sreg_ntid_y(),
        gdimz = @|| nvvm_read_ptx_sreg_nctaid_z() * nvvm_read_ptx_sreg_ntid_z(),
        nblkx = nvvm_read_ptx_sreg_nctaid_x,
        nblky = nvvm_read_ptx_sreg_nctaid_y,
        nblkz = nvvm_read_ptx_sreg_nctaid_z
    },
    exec = @|body| |grid, block| {
        nvvm(dev, grid, block, body)
    },
    sync          = @|| synchronize_cuda(dev),
    alloc         = @|size| alloc_cuda(dev, size),
    alloc_unified = @|size| alloc_cuda_unified(dev, size),
    barrier       = nvvm_barrier
};
```

Btw, we can change the name "work" to something else. 

I would be in favor of this, instead of my original PR.

**Comment by richardmembarth** [comment]
How would you provide the kernel name here?

**Comment by PearCoding** [comment]
Example code:

```
fn my_kernel() {
  let work_item = acc.work;
  // ...
}
acc.exec(grid, block, my_kernel);
```

The kernel will be named "my_kernel_....". It has a hash based suffix (as usual).

**Comment by PearCoding** [comment]
Dropped in favour of properly handling names in Artic and propagating it in the future.

**Pull request closed without merging**
