### PR TITLE
Unified artic and impala runtime

### PR DESCRIPTION
**Pull request by richardmembarth**
This unifies the artic and impala runtimes:
- frontend-specific files are in and `platforms/artic` and `platforms/impala`
- `anydsl_runtime_wrap` works as before for impala
- `anydsl_runtime_wrap` allows to specify `FRONTEND` (artic, impala - default)
- `anydsl_runtime_wrap` allows to specify `ARTIC_FLAGS`
- two jit libraries: `runtime_jit_artic` and `runtime_jit_impala`

When using jit, the user needs to link against the proper artic or impala jit library `AnyDSL_runtime_ARTIC_JIT_LIBRARIES` or `AnyDSL_runtime_IMPALA_JIT_LIBRARIES` and include `anydsl_jit.h` instead of `anydsl_runtime.h`.

### CODE REVIEW

**Review by madmann91 — APPROVED** [review]
The PR looks good. It would be nice to only build the JIT library that we have (i.e. if you have only impala, then only build `libruntime_jit_impala`). But I guess we can already merge as-is.

**Comment by richardmembarth** [comment]
This is already the case: The individual JIT libraries are only built if artic or impala are found.

**Comment by madmann91** [comment]
Ah, I thought that was an error, but it's only a warning. Still, I could not find a wait to tell CMake to stop emitting this warning, even with the `QUIET` option.

**Comment by stlemme** [comment]
I fixed/improved a couple of issues. From my point of view, the PR is ready to be merged.

Anyways, we shall revisit the LLVM dependency chain of specific runtime features to have the minimal required dependencies, but this can take place at a later stage.

**Review by stlemme — APPROVED** [review]

**Pull request merged**
